using UnityEngine;

public class Play : MonoBehaviour
{
    public bool IsOnPlatform = false;
    
    // Kollar om spelaren 채r p책 plattformen "playButton"
    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.name == "playButton")
        {
            IsOnPlatform = true;
        }
    }

    void OnCollisionExit(Collision collision)
    {
        if (collision.gameObject.name == "playButton")
        {
            IsOnPlatform = false;
        }
    }


    void Start()
    {
       
    }

    // Update is called once per frame
    void Update()
    {
        if (IsOnPlatform == true)
        {
            Debug.Log("Spelaren 채r p책 playButton-plattformen");
        }
    }
}

